### ISSUE TITLE
Wrong checksum is size >= 2,147,483,647

### ISSUE THREAD

**Issue by newtoncorp** [OneOfOne/xxhash#13]
After updating the golang version and pulling from git we have encountered an issue with checksums of data size bigger than 2,147,483,647 bytes.

with the following code :
> package main
> 
> import (
>     "github.com/OneOfOne/xxhash"
>     "os"
>     "io"
>     "fmt"
>     "flag"
> )
> 
> func main() {
> var name string
> flag.StringVar(&name, "filename", "", "")
> flag.Parse()
>     t, _ := os.Open(name)
>     h := xxhash.New64()
>     io.Copy(h, t)
>     fmt.Print(h.Sum64())
> }

By comparing with the python version which works correctly and from random data (` dd if=/dev/urandom of=test-rd count=1048576 bs=2048`) we get the following :
- 11325124925539256852 (python3.4.3 xxhash)
- 11833478386888335343 (golang1.6.1)
running the dd command again :
- 430381004049939737 (python3)
- 11833478386888335343 (golang1.6)

And here the checksums are correct (` dd if=/dev/urandom of=test-rd count=1048575 bs=2048`: 
1705419376331282536 (for both)

**Comment by OneOfOne** [comment]
Can you try with go 1.8 or 1.7 and see if you notice the same behavior? I'll try to look into it.

**Comment by newtoncorp** [comment]
Same behavior with go 1.8, also same behavior with using a loop instead of io.Copy.

**Comment by newtoncorp** [comment]
Hello,

Did you have time to look into this ?

**Comment by OneOfOne** [comment]
Sorry didn't have time.

**Comment by newtoncorp** [comment]
Hello,

I've think I've found out what happened.
It's with this commit : https://github.com/OneOfOne/xxhash/commit/a625d8a751fb34a650f7537a2b0b6c44fca16ca2

In `XXHash64 struct` you've replaced `ln uint64` by `ln, memIdx     int32`. 
So https://github.com/OneOfOne/xxhash/blob/master/xxhash.go#L103 should be a uint64.

There's also an int32 cast in https://github.com/OneOfOne/xxhash/blob/master/xxhash_go17.go#L238 that might cause issues.

Is this analysis correct ?

**Comment by thedrow** [comment]
@newtoncorp It looks like you are correct. @OneOfOne will you accept a PR fixing this?

**Comment by OneOfOne** [comment]
@thedrow PRs are accepted, I've been very busy.

**Comment by OneOfOne** [comment]
@newtoncorp please test and reopen if that's not the issue, if you can create a minimal test case It'd be great.
