### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by kron4eg** [OneOfOne/xxhash#19]
Hello,

I'm looking at https://github.com/OneOfOne/xxhash/compare/v1.2...master and wandering, maybe it's time for new release/tag? So dep could pick up newer version. What do you think?

**Comment by OneOfOne** [comment]
I haven't used dep myself, so I didn't realize people who uses it depended on tags.

I'll create a release now and I'll make sure when i finish the rewrite (with go 1.10 release, hopefully the inliner will be smart enough so the code can be properly split up).

**Comment by kron4eg** [comment]
Thank you very much!
