### ISSUE TITLE
get hash of full object if i have parts

### ISSUE THREAD

**Issue by vtolstov** [OneOfOne/xxhash#20]
Hi. I have file 16Mb and hashes for each Mb (16 items) Does it possible to get complete hash for 16Mb using this 1Mb hashes or i need to recalc for all 16Mb ?

**Comment by OneOfOne** [comment]
You can use the [`New64`](https://godoc.org/github.com/OneOfOne/xxhash#New64) and call .Write multiple times as needed, then call [`Sum64`](https://godoc.org/github.com/OneOfOne/xxhash#XXHash64.Sum64) when you're done.

https://play.golang.org/p/316ziQB2ibX here's a little example that shows how you can use it.

**Comment by vtolstov** [comment]
Thanks, but if i don't want to recalculate all blocks that i already have hash?

**Comment by vtolstov** [comment]
And what purpose of seed  in NewS64 ?

**Comment by OneOfOne** [comment]
> Thanks, but if i don't want to recalculate all blocks that i already have hash?

OH, sorry but no that's not possible, I misunderstood the original comment.

> And what purpose of seed in NewS64 ?

That's the initial seed used by the hash algorithm, mainly used if you want to avoid collision by adding an extra "const" to your hashing, default is 0.

**Comment by vtolstov** [comment]
Ok, thanks!
