### ISSUE TITLE
OneOfOne and cespare xxhash implementations give different results

### ISSUE THREAD

**Issue by pborman** [OneOfOne/xxhash#21]
It appears that when using the Write interface for multiple blocks of data, this xxhash and the @cespare xxhash produce different results.  For a single block they do agree.

The following test program demonstrates the issue:

```
package hash_test

import (
	"testing"

	xx2 "github.com/OneOfOne/xxhash"
	xx1 "github.com/cespare/xxhash"
)

var lines = [][]byte{
	[]byte("Lorem ipsum dolor sit amet, consectetuer adipiscing elit."),
	[]byte("Aenean commodo ligula eget dolor. Aenean massa."),
}

func TestHashImplementations(t *testing.T) {
	h1 := xx1.New()
	h2 := xx2.New64()
	for i, line := range lines {
		s1 := xx1.Sum64(line)
		s2 := xx2.Checksum64(line)
		if s1 != s2 {
			t.Errorf("line %d single: %x != %x\n", i, s1, s2)
		}
		h1.Write(line)
		h2.Write(line)
		var b1, b2[8]byte
		copy(b1[:], h1.Sum(nil))
		copy(b2[:], h2.Sum(nil))
		if b1 != b2 {
			t.Errorf("line %d composite: %x != %x\n", i, b1, b2)
		}
	}
}
```

The output is:

```
--- FAIL: TestHashImplementations (0.00s)
	hash2_test.go:30: line 1 composite: b70cd033547f374d != fefd5c3b483cdc2a
FAIL
```

**Comment by cespare** [comment]
On my machine (using latest copies of both libraries) your test case passes. (Both give b70cd033547f374d, which is correct.)

It looks like your copy of OneOfOne/xxhash was giving the wrong answer, but I can't repro with or without the `safe` build tag.

What version of OneOfOne/xxhash are you using? What arch are you on? Are you using any build tags?

**Comment by pborman** [comment]
Thanks, it turns out I had thought I had pulled the latest from GitHub, but my copy of OneOfOne/xxhash was:

```
commit 9f129ced0523605cdde14a954ae4609e366a7998
Author: OneOfOne <oneofone@gmail.com>
Date:   Tue Jun 20 19:53:52 2017 +0200
```

So apparently back between June 21 and Aug 18 I did a ```go get``` on it.

Sorry for the noise and thank you for looking into it.

**Comment by OneOfOne** [comment]
@cespare thanks for looking into it!
@pborman thanks for the report.

I completely missed this email.
