### ISSUE TITLE
'type [2147483647]byte larger than address space' when cross compiling

### ISSUE THREAD

**Issue by Thyaris** [OneOfOne/xxhash#22]
When cross compiling for `linux-ppc64le` or `linux-mipsle`, the error `/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:20:23: type [2147483647]byte larger than address space` occurs.

Command:
`GOOS=linux GOARCH=ppc64le go build -o executable main`

**Comment by OneOfOne** [comment]
@Thyaris I'm not sure how to fix that for ppc64* except by disabling the unsafe optimizations for those archs, would that be fine with you?

Of course any patches are welcome.

**Comment by OneOfOne** [comment]
Also does your program work if you use `GOOS=linux GOARCH=ppc64le go build -tags safe -o app`?

**Comment by Thyaris** [comment]
Actually I cannot reproduce this behaviour anymore... But maybe you can try that when you have the time.
I was using the docker image `golang:1.10.0`, and the code that was causing the error (cause that is the only location in the code that I use xxhash):
```
func (self *Bean) XXHashSum() ([]byte, error) {
	bytes, err := ioutil.ReadAll(self.file)
	if err != nil {
		return "", errors.New("Couldn't compute file hash, of " + self.uuid.String())
	}
	return XXHash(bytes), nil
}

func XXHash(input []byte) []byte {
	xxhash := xxhash.New64()
	return xxhash.Sum(input)
}
```

Considering my project, you can remove the unsafe optimizations. We do not have consumers that actually use linux-ppc64le or mipsle, we just have it in our build-process because it's officially supported by Go.
Considering your source code, `-tags safe` should fix the problem.






The logs were:
```
Building datacenter-linux-ppc64le...
# github.com/OneOfOne/xxhash
/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:20:23: type [2147483647]byte larger than address space
/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:29:20: type [2147483647]byte larger than address space
/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:39:23: type [2147483647]byte larger than address space
/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:47:20: type [2147483647]byte larger than address space
Building datacenter-linux-mipsle...
# github.com/OneOfOne/xxhash
/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:20:23: type [2147483647]byte larger than address space
/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:29:20: type [2147483647]byte larger than address space
/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:39:23: type [2147483647]byte larger than address space
/root/go/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:47:20: type [2147483647]byte larger than address space
```

Feel free to close this issue.

**Comment by OneOfOne** [comment]
Alright fair enough.

Your code is wrong btw, your XXHash func is returning the input + appended empty hash rather than the hash of the input.

```
func XXHash(input []byte) []byte {
	xxhash := xxhash.New64()
	xxhash.Write(input)
	return xxhash.Sum(nil)
}
```

Also if you're hashing a file, you might want to use io.Copy on an `xxhash.New64` object rather than using `ioutil.ReadAll`, something along the lines of:

```
// not tested
func (self *Bean) XXHashSum() ([]byte, error) {
    f, err := os.Open(self.file)
    if err != nil {
        return nil, errors.New("Couldn't compute file hash, of " + self.uuid.String())
    }
    defer f.Close()
    xx := xxhash.New64()
    io.Copy(xx, f)
    return xx.Sum(), nil
}
```

**Comment by Thyaris** [comment]
Thank you for that

**Comment by OneOfOne** [comment]
Fixed (well, workaround) in https://github.com/OneOfOne/xxhash/commit/c8a32011bfcbf736aeb27d5d077ed081a3626964
