### ISSUE TITLE
TestSum64 test fails on bigendian

### ISSUE THREAD

**Issue by ajay-ibm** [OneOfOne/xxhash#24]
I am running the test using `go test -v` on my s390x system. Logs are below:
```
=== RUN   Test
--- PASS: Test (0.00s)
        xxhash_test.go:34: xxhash backend: GoUnsafe
        xxhash_test.go:35: Benchmark string len: 2235
=== RUN   TestHash32
--- PASS: TestHash32 (0.00s)
=== RUN   TestHash32Short
--- PASS: TestHash32Short (0.00s)
=== RUN   TestWriteStringNil
--- PASS: TestWriteStringNil (0.01s)
=== RUN   TestSum64
--- FAIL: TestSum64 (0.00s)
        xxhash_test.go:99: [i=4,chunkSize=1] got 0x84140adb817143db; want 0x415872f599cea71e
FAIL
exit status 1
FAIL    github.com/OneOfOne/xxhash 0.035s

```
I think the function `New64()`  produces different result on bigendian. Can someone help me on this?

**Comment by OneOfOne** [comment]
Any news on this? I can't really test on bigendian, does it work correctly with `-tags safe`?

**Comment by kcrane** [comment]
I've tested this on s390x system and `-tags safe` does pass (and verified `-tags unsafe` failed).

I have also verified that using build constraints `s390x`/`!s390x` in respective safe/unsafe files fixed the default build on s390x system.

**Comment by OneOfOne** [comment]
@kcrane please let me know if you need anything else changed.
