### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by charkost** [OneOfOne/xxhash#25]
Hello,

It will be useful to create a new tag which will include 2c166c65.

The [debian package for xxhash](https://tracker.debian.org/pkg/golang-github-oneofone-xxhash) relies on tags for its versioning. So it needs a new tag to include this fix.

The new tag will help us fix the [build errors](https://buildd.debian.org/status/fetch.php?pkg=burrow&arch=mips&ver=1.2.0-1&stamp=1548676161&raw=0) on mips for debian.

**Comment by OneOfOne** [comment]
Done, https://github.com/OneOfOne/xxhash/releases/tag/v1.2.3

**Comment by OneOfOne** [comment]
@charkost I'm thinking about doing some clean up, what's the min compiler version I need to support for debian?

**Comment by charkost** [comment]
@OneOfOne thanks for quickly resolving the issue. 1.11 is the min compiler version. 
Note that [debian is about to freeze](https://lists.debian.org/debian-devel-announce/2019/01/msg00008.html) at the end of this month and new upstream versions will not be able to make it to the next debian stable release after the freeze.

**Comment by OneOfOne** [comment]
That is perfect, I was worried it'd be 1.8 or something like that, you never know with debian.
