### ISSUE TITLE
[PENDING] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [OneOfOne/xxhash#26]
Dear Ahmed,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by OneOfOne** [comment]
Windows binary of what? xxsum?

**Comment by sergeevabc** [comment]
Indeed, Ahmed. To let users touch the innovation and hash the input.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by OneOfOne** [comment]
So apparently `Fixed #xx` doesn't work in release notes... 

https://github.com/OneOfOne/xxhash/releases/tag/v1.2.5
