### ISSUE TITLE
runtime error: unsafe pointer conversion

### ISSUE THREAD

**Issue by rjammala** [OneOfOne/xxhash#27]
Hi @OneOfOne 

See this error when running with the race detector using this version of Go:

go version devel +3c0fbee Tue Nov 5 05:22:07 2019 +0000 linux/amd64

2019/11/05 10:30:22 http: panic serving host:41960: runtime error: unsafe pointer conversion
goroutine 28 [running]:
net/http.(*conn).serve.func1(0xc0003701e0)
	/home/ubuntu/repos/go/src/net/http/server.go:1772 +0x147
panic(0xe59c20, 0xc0001d4140)
	/home/ubuntu/repos/go/src/runtime/panic.go:967 +0x396
github.com/OneOfOne/xxhash.(*XXHash64).WriteString(0xc000306060, 0xc0001da0f0, 0xa, 0x7fef142c9028, 0xc000306060, 0x1)
	/home/ubuntu/go/pkg/mod/github.com/!one!of!one/xxhash@v1.2.5/xxhash_unsafe.go:52 +0x90
io.WriteString(0x111c9c0, 0xc000306060, 0xc0001da0f0, 0xa, 0x7fef1a51b008, 0xc0001e2760, 0x7fef142c9008)
	/home/ubuntu/repos/go/src/io/io.go:291 +0x82
strings.(*Reader).WriteTo(0xc0001d4120, 0x111c9c0, 0xc000306060, 0x7fef142c9008, 0xc0001d4120, 0x1)
	/home/ubuntu/repos/go/src/strings/reader.go:137 +0x141
io.copyBuffer(0x111c9c0, 0xc000306060, 0x111d3a0, 0xc0001d4120, 0x0, 0x0, 0x0, 0x5dc14f3e, 0xc0001da0f0, 0xa)
	/home/ubuntu/repos/go/src/io/io.go:387 +0x47f
io.Copy(...)
	/home/ubuntu/repos/go/src/io/io.go:364
main.hashString(0xc0001da0f0, 0xa, 0x0)
	/home/ubuntu/repos/code/main.go:713 +0x288
main.main.func2(0x11278a0, 0xc0002ea8c0, 0xc0001c2400)
	/home/ubuntu/repos/code/main.go:1531 +0x90b
net/http.HandlerFunc.ServeHTTP(0xedde38, 0x11278a0, 0xc0002ea8c0, 0xc0001c2400)
	/home/ubuntu/repos/go/src/net/http/server.go:2012 +0x52
net/http.(*ServeMux).ServeHTTP(0x1629300, 0x11278a0, 0xc0002ea8c0, 0xc0001c2400)
	/home/ubuntu/repos/go/src/net/http/server.go:2387 +0x289
net/http.serverHandler.ServeHTTP(0xc0002ea620, 0x11278a0, 0xc0002ea8c0, 0xc0001c2400)
	/home/ubuntu/repos/go/src/net/http/server.go:2807 +0xcf
net/http.(*conn).serve(0xc0003701e0, 0x112a7e0, 0xc0001a11c0)
	/home/ubuntu/repos/go/src/net/http/server.go:1895 +0x838
created by net/http.(*Server).Serve
	/home/ubuntu/repos/go/src/net/http/server.go:2932 +0x5c0

**Comment by OneOfOne** [comment]
That's due to the new checkptr runtime check in 1.14 (git), it's not an actual race or a bug, but I still didn't find a workaround, I'm still looking into it.

**Comment by OneOfOne** [comment]
Should be fixed by https://github.com/OneOfOne/xxhash/releases/tag/v1.2.6, reopen if you run into this issue again.
