### ISSUE TITLE
Make New32 and New64 return hash.Hash

### ISSUE THREAD

**Issue by ycombinator** [OneOfOne/xxhash#29]
Would it be possible to make the [`xxhash.New32`](https://github.com/OneOfOne/xxhash/blob/8f0be54a8d5ccf68817143d8c996147ec5cbd795/xxhash.go#L65) and [`xxhash.New64`](https://github.com/OneOfOne/xxhash/blob/master/xxhash.go#L125) functions return `hash.Hash` instead of `*XXHash32` and `*XXHash64` respectively?  

This would bring them in line with other hash implementations in golang, making it easy to consume them in projects that use multiple hash implementations, e.g. https://github.com/elastic/beats (see https://www.elastic.co/guide/en/beats/filebeat/master/fingerprint.html).

**Comment by OneOfOne** [comment]
That's a fair request, but I'm not sure it'd break current users.

How do you feel about 2 new funcs like `NewHash{32,64}`?

**Comment by ycombinator** [comment]
I think 2 new functions are a good solution to preserving backwards compatibility. Thanks!

**Comment by OneOfOne** [comment]
Also pushed a new tag `v1.2.7` with this fix.

**Comment by ycombinator** [comment]
Thanks for the super fast turnaround ❤️!

**Comment by rvillablanca** [comment]
Thanks @OneOfOne
