### ISSUE TITLE
Unable to write more than 1G of data using CGO engine

### ISSUE THREAD

**Issue by newtoncorp** [OneOfOne/xxhash#9]
See : https://github.com/OneOfOne/xxhash/blob/master/xxhash_cgo.go#L111

This limitation does not apply on the pure GO engine.
Looking at the code in https://github.com/OneOfOne/xxhash/blob/master/c-trunk/xxhash.c#L875 which uses a size_t, the standard defines it as a unsigned integer with at least 16 bits. Usually it's 32bits on 32bit arch and 64bits on 64bit arch. Why is there a limit of 1G ? Either the limit is 16bits wide or the same as integer in go.

Ref (https://en.wikipedia.org/wiki/C_data_types#Size_and_pointer_difference_types)

**Comment by OneOfOne** [comment]
I swear there was a reason for that, but for the life of me I can't find it now.

I'll remove the limit
